### ISSUE TITLE
Problem with previously working script: isolineslice

### ISSUE THREAD

**Issue by rpandress** [precise-simulation/featool-multiphysics#12]
Some months back, under the Basic forum topic: "**Slice Plot of 3D Result Showing Iso Contour Lines on a Slice**", with your help, I developed a script called "**isolineslice**" that plots orthogonal, planar slice of FEATool result using iso lines/contours and optionally adds color band contours. I have also added a customized log vs. linear scale option.

I occasionally want to use this script even though we now have the Post-->Slice Plot option.

```
Usage: isolineslice (PROB, evalexpr, orthoplane, val, lvl, scale, cmap, viewdim, addcolors)
       PROB:       fea, the variable exported by FEAtool
       evalexpr:	the mathematical expression to be evaluated and plotted
                   such as 's_dc*sqrt(Vx^2+Vy^2+Vz^2)', current density A/m^2
       orthoplane:	'XY', 'YZ', or 'XZ' to denote orientation of slice plane
       val:        value of the invariant coordinate in the plane
                       (e.g., for 'XY', z is invariant) e.g., 0.5
       lvls:       the number of iso levels to plot on the plane, e.g., 20
       scale:      'lin' for linear or 'log', for log10
       cmap:       the color map to be used (for both 3D and 2D plots)
                   e.g., 'jet'
       viewdim:    (==2 for 2D, ==3 for 3D; actually <3 for 2D & ~<3 for 3D)
       addcolors:  (==1) Add colored gradient contour bands.
 
       Example:	isolineslice(fea, 's_dc*sqrt(Vx^2+Vy^2+Vz^2)', 'XY', 0.0, 15, 'lin', 'jet', 2, 1)
```
In reviewing and re-familiarizing myself with this script, I have encountered a problem (or limitation) that I do not recall from my earlier work.  I'm not sure if I am misusing it, using it on a geometry that it never did work for, or something has changed in my environment (I am using the latest FEATool release ver 1.14.3, build 21.08.242 from MATLAB 2020a.

If I am correct in my analysis, the problem occurs when the array of objects returned from "postplot" contains multiple patches and the subsequent calls to findall patches and get the vertices is made with an array of patches for an argument in stead of a single patch:

```
h = findall(h,'type','patch');   % Get graphics handle to patch/slice.

% Create 2D grid.
grid.p = get(h,'Vertices')';
```
For example, the following was extracted from the debugger in a case where three patches are included in the findall return, using the following call to **isolineslice_loop** with the "fea" from the attached model file **cyl_small_in_large_in_box.fea**.

```
isolineslice_loop(fea, 'V', 'YZ', 0.325, 15, 'lin', 'cool', 2, 0)

h = 

  3×1 Patch array:

  Patch    (fea_slice)
  Patch    (fea_slice)
  Patch    (fea_slice)

K>> h(1)

ans = 

  Patch (fea_slice) with properties:

    FaceColor: 'interp'
    FaceAlpha: 1
    EdgeColor: [0 0 0]
    LineStyle: 'none'
        Faces: [1150×3 double]
     Vertices: [805×3 double]
```
In order to investigate this, I have modified isolineslice_loop to make a 2D plotting pass for each of the patches, which, if combined with the same scale, might give the desired result.

As this is my first post on the github forum, please let me know how I might correct or improve content and/or style.

Kind regards,
-Randal

[cyl_small_in_large_in_box.zip](https://github.com/precise-simulation/featool-multiphysics/files/7230642/cyl_small_in_large_in_box.zip)
[isolineslice_loop.zip](https://github.com/precise-simulation/featool-multiphysics/files/7230643/isolineslice_loop.zip)

**Comment by precise-simulation** [comment]
Dear Randal,

I'm assuming with problem, you mean that you get 3 individual slice plots instead of all of them in one.

There were some changes in the last updates to fix plotting with deactivated subdomains, so basically all plots are made individually over subdomains. Hence three patches from your model (as it has three subdomains).

To plot all in one figure in your script you could just lift the `f2 = figure();` creation statement to outside the for `i=1:h_len` loop.

Let me know if I understood the problem correctly.

**Comment by rpandress** [comment]
Sorry I was not clear on just what I considered to be  the problem :-).
> I'm assuming with problem, you mean that you get 3 individual slice plots instead of all of them in one.

Before, I would get a single-unified plot of all the data that intersected the slice, just as the `Post-->Slice Plot` does.

Now, by recognizing that there could be multiple patches, I can get a plot of any or all of them - I can even glue them together on a single figure (thanks to you for suggesting I move `f2 = figure;` outside the loop).  But the iso lines are not unified (part of a single scaled set of lines) but are simply the visual sum of the line pictures that were created for each individually scaled plot. Additionally, I'd like to eliminate the 2D subdomain outlines from views not being plotted.

I hope that is clearer.  I have included the `Post-->Plot Slice` result and the **isolineslice**_loop result to illustrate the difference.  Again, before (1.13?) my plot and yours looked VERY similar.

I think what I want is (or is the equivalent of) combining the patches in to a single patch and then doing a single plot without the loop, so that I get the same results as before (and as you get still with `Post-->Slice PLot`).

Kind regards,
Randal

![FEATool_Slice_Plot](https://user-images.githubusercontent.com/89186213/134817196-d4266d9d-e198-4d99-b534-611b74fbf378.png)
![isolineslice_loop](https://user-images.githubusercontent.com/89186213/134817201-14e34caf-9e99-4cfe-bdca-36ff543e0ec9.png)

**Comment by rpandress** [comment]
> I think the issue is that you make contours on the data range in each patch (that is 15 levels in the range in the patch), you could either specify the actual levels [-10:2:10], or extract and merge the patch data to your fea2 struct with something like

```
p = []; f = []; u = []; offset = 0;
for i=1:length(h)
  p = [p; get(h(i),'Vertices')];
  f = [f; get(h(i),'Faces')+offset];
  u = [u; get(h(i),'FaceVertexCData')]
  offset = size(p,1);
end
```

Yes, that is what I think.  But I am going to need a little more help.

I find that if I transpose 'p' and 'f' that for a length(h) of 1, this produces the desired result.  However for lengths greater than 1 it does not.  

Is it possible that the transposition is still a problem within the combining loop?

Kind regards,
Randal

**Comment by precise-simulation** [comment]
Well, if you extract the data you can just ignore h and skip the loop.

    p = []; f = []; u = []; offset = 0;
    for i=1:length(h)
      p = [p; get(h(i),'Vertices')];
      f = [f; get(h(i),'Faces')+offset];
      u = [u; get(h(i),'FaceVertexCData')];
      offset = size(p,1);
    end
    
    grid.p = p';
    grid.c = f';
    grid.a = gridadj(grid.c,2);
    grid.b = gridbdr(grid.p,grid.c,grid.a);
    grid.s = ones(1,size(grid.c,2));
    
    ...
    
    if isequal(scale, 'log')
      fea2.sol.u = log10(u);
    else
      fea2.sol.u = u;
    end

**Comment by rpandress** [comment]
> you can just ignore h and skip the loop 

I think I have done so (see attached), but I still have something wrong ...
[isolineslice_combine.zip](https://github.com/precise-simulation/featool-multiphysics/files/7242007/isolineslice_combine.zip)

**YZ plane slice at x=0.6**
Our plots match pretty well. Note color bar scale.
Post-->Slice Plot:
![FEATool_Slice_Plot_x6](https://user-images.githubusercontent.com/89186213/135046732-f8531868-0290-4c09-8bce-5dc1bb54b0e4.png)

isolineslice_combine:
![isolineslice_combine_x6](https://user-images.githubusercontent.com/89186213/135046737-d7f5daef-fbdb-48fb-91c9-ae626a5584bb.png)

**YZ plane slice at x=0.39**
isolinesplce_combine is similar but not correct:
Post-->Slice Plot:
![FEATool_Slice_Plot_x39](https://user-images.githubusercontent.com/89186213/135046735-8ca7864d-c514-48f5-9530-6fa2e3e70763.png)

isolineslice_combine:
![isolineslice_combine_x39](https://user-images.githubusercontent.com/89186213/135046738-e04004e9-20d6-4b99-97f6-a35e367b5745.png)

Something still has me stumped (not hard to do, I'm afraid)

Thanks for taking another look,
-Randal

**Comment by precise-simulation** [comment]
In this case your function is plotting "correct" due to extracting the data directly from the 3D slice plot. Compare the range by plotting the same expression as a 3D slice. The 2D slice plot is currently plotting "averaged" over all domains at once giving different results. This will be corrected in the next update. Be aware that you are plotting a gradient that is discontinuous over domains (through s_dc) which is very sensitive.

**Comment by rpandress** [comment]
As always, thanks for the analysis and explanation, which I completely accept, even though I do not completely understand :-)

Do I  understand correctly that you plan to make a change that will enable the script to work as before (about 9 months ago) by using the same technique as the isolineslice_combine included with the last post?

 I hope to be able to produce plots such as I used to such these which plot iso lines seemingly continuously across subdomain boundaries:
![rotate2D](https://user-images.githubusercontent.com/89186213/135140954-6baa2a20-1ea9-44dd-8639-8300ff5174b5.png)
and
![YZcurrentDensityXYgeometry](https://user-images.githubusercontent.com/89186213/135141022-3681380d-b2d6-4994-b61f-2381290ad5ae.png)

Going back to an earlier reply you suggested:  
> you could either specify the actual levels [-10:2:10], 

Could I achieve the result I am seeking now by doing that: discarding the patch combine loop and going back to loop over h(n), specifying the same level on each and plotting them on the same figure?

Thanks again,
-Randal

**Comment by precise-simulation** [comment]
> Do I understand correctly that you plan to make a change that will enable the script to work as before (about 9 months ago) by using the same technique as the isolineslice_combine included with the last post?

No, extracting data from plots and using it as a workaround like your script does is officially unsupported functionality. 
As such your script may or may not work as expected in the future. Unfortunately, it is not feasable to develop with full compatibility for custom user scripts in mind (as such scripts can literally do anything). I'm closing this issue as it technically is not an issue with the software itself.
