### ISSUE TITLE
Help with plotsubd

### ISSUE THREAD

**Issue by rpandress** [precise-simulation/featool-multiphysics#13]
Exporting 'fea' from this model:
[cyl_small_in_large_in_box.zip](https://github.com/precise-simulation/featool-multiphysics/files/7246027/cyl_small_in_large_in_box.zip)
![cyl_small_in_large_in_box](https://user-images.githubusercontent.com/89186213/135131329-676484ca-af00-41e4-be39-acd7cdd49064.png)

and executing this command:
`>> plotsubd(fea, 'alpha', 0.3, 'selsubd', [2], 'parent', figure())`

gives this result:
![plotsubd](https://user-images.githubusercontent.com/89186213/135130605-38f23f3b-10a4-49eb-9b21-0a06339ede23.png)

Not what I was expecting.   I get the same result no matter what subdomain I specify, such as `'selsubd', [1] `or `'selsubd', [3]`.

What am I doing wrong(?),
Randal

**Comment by precise-simulation** [comment]
The _selsubd_ parameter does not currently do anything in 3D. The object patches are tagged "fea_patch_d#" so you can extract them and set their visibility manually, for example

    set(findall(0,'tag','fea_patch_d1'), 'visible', 'off')
