### ISSUE TITLE
Error when Post-->Min/Max Evaluation... in version 1.4.3 (build 21.08.242)

### ISSUE THREAD

**Issue by rpandress** [precise-simulation/featool-multiphysics#16]
When post processing and attempting to calculate the min/max current density the following error presented:
![W10_1p14p3_minmaxError](https://user-images.githubusercontent.com/89186213/135809962-77ffb46a-d738-487c-801b-7c208a1a0df9.png)

[**Edited**]The solved model file using version 1.14.3 (build 21.08.242) and MATLAB 2020a, Windows 10:
[cylinders_between_cylinders_in_boxv1_from_geom3.zip](https://github.com/precise-simulation/featool-multiphysics/files/7276246/cylinders_between_cylinders_in_boxv1_from_geom3.zip)

[Added/Edit]
On further investigation as to what could be different, I noted that the gridgen tool for the 1.14.3 solution was "Built-in" but was Gmsh for the 1.13.0 solution.  After changing the 1.14.3 model to Gmsh the min/max could be calculated without error, but they differ significantly from the 1.13.0 values.
1.14.3 min/max:
```
Minima of expression s_dc*sqrt(Vx^2+Vy^2+Vz^2) : 0.0821719 at ( 0.355083, 0.623566, 0.657053)
Maxima of expression s_dc*sqrt(Vx^2+Vy^2+Vz^2) : 1.84506 at ( 0.6, 0.564645, 0.535355 )
```

1.13.0 min/max:
```
Minima of expression s_dc*sqrt(Vx^2+Vy^2+Vz^2) : 0.0818047 at ( 0.659267, 0.462183, 0.303608) 
Maxima of expression s_dc*sqrt(Vx^2+Vy^2+Vz^2) : 1.93679 at ( 0.4, 0.4, 0.55 )
```
When I changed the 1.13.0 model gridgen tool to Built-in, the gridgen failed:
![W7_1p13p0_BuiltIn_gridgen_err](https://user-images.githubusercontent.com/89186213/135824073-931089d1-bad4-457c-99cb-06e97cd2c97e.png)

[I suspect the following may be caused by the same issue. If not please create a separate issue.]

In addition, the Postprocessing slice option:
![W10_1p14p3_PostPlot_SliceSetting](https://user-images.githubusercontent.com/89186213/135811643-3df26cea-a1d6-4a77-8252-eecdde0629da.png)

...does not appear to be correct:
![W10_1p14p3_PostPlot_Slice](https://user-images.githubusercontent.com/89186213/135811700-edc907e6-a3c2-4e8d-9b27-c0792328406f.png)

[**Edited**]The result using version1.13.0 (build 20.12.350):
![W7_1p13p0_PostPlot_SliceSettings](https://user-images.githubusercontent.com/89186213/135811859-c6776137-201f-4063-976e-a01046f244ce.png)

...seems correct:
![W7_1p13p0_PostPlot_Slice](https://user-images.githubusercontent.com/89186213/135811903-f961f581-0dc8-4bc8-a43d-b6bd140b94cb.png)

Solved model from  using version 1.13.0 (build 20.12.350) and MATLAB 2019a, Windows 7:
[cylinders_between_cylinders_in_boxv1_save_solved.zip](https://github.com/precise-simulation/featool-multiphysics/files/7276333/cylinders_between_cylinders_in_boxv1_save_solved.zip)

[Once again, I suspect the following is related.]
Post-Slice Plot... for 1.14.3:
![W10_1p14p3_isoPlot surface](https://user-images.githubusercontent.com/89186213/135812613-91d68985-4a9d-4758-bcec-3851b293583c.png)

...which differs from that from 1.13.0:
![W7_1p13p0_isoPlot surface](https://user-images.githubusercontent.com/89186213/135812743-f42aa7e9-43d8-47ce-a2d4-13ea8b72e905.png)

And with iso contours only, 1,14,3:
![W10_1p14p3_isoPlot](https://user-images.githubusercontent.com/89186213/135813979-ba5b5651-e12e-44f7-aa40-f7893272da60.png)

vs for 1.13.0
![W7_1p13p0_isoPlot](https://user-images.githubusercontent.com/89186213/135813255-366a32ae-15f2-4001-b6a7-cd64243100d6.png)

These are of course very similar and perhaps by reducing an appropriate convergence criteria, would be much closer.

Thanks in advance for checking into this and ...
Kind regards,
Randal

**Comment by rpandress** [comment]
Have you been able to reproduce this issue? Is there anything further that I could do that would be helpful?

Kind regards,
Randal

**Comment by precise-simulation** [comment]
I have not been able to reproduce the error message, and as mentioned in your other issues improvements to slice plots will be available in the next release.

**Comment by rpandress** [comment]
> I have not been able to reproduce the error message, 

In reading over my original post, I noticed that I incorrectly listed Windows 7 as the operating system being used with 1.14.3 when getting the Min/Max error.   

My apologies for the confusion I created by my sloppy posting.

I have just made a correction via the Edit feature to correct the Min/Max error Windows version that I was using to Windows 10 (not Windows 7).
> [Edited]The solved model file using version 1.14.3 (build 21.08.242) and MATLAB 2020a, Windows 10:

Does that make any difference? 

Do you now get this error using Windows 10 (and 1.14.3 b21.08.242) when using the **Built-in** gridgen tool? 
![W10_1p14p3_minmaxError](https://user-images.githubusercontent.com/89186213/135809962-77ffb46a-d738-487c-801b-7c208a1a0df9.png)
If not, what Min/Max values do you get?

What does your Postprocessing Options:Slice Plot
![W10_1p14p3_PostPlot_SliceSetting](https://user-images.githubusercontent.com/89186213/135811643-3df26cea-a1d6-4a77-8252-eecdde0629da.png)

... look like?
![W10_1p14p3_PostPlot_Slice](https://user-images.githubusercontent.com/89186213/135811700-edc907e6-a3c2-4e8d-9b27-c0792328406f.png)

>  and as mentioned in your other issues improvements to slice plots will be available in the next release.
Do you have a rough estimate as to when this might be?

Thanks for looking into this and ....
Kind regards,
Randal

**Comment by precise-simulation** [comment]
From the error message and model logs it looks like you have tried to evaluate the whole string expression:

"Minima of expression                   s_dc*sqrt(Vx^2+Vy^2+Vz^2) ..."

not only "s_dc*sqrt(Vx^2+Vy^2+Vz^2)". The error message echoes exactly what is put into the edit field (but you might only see part of it due to limited space).

If you can reproduce the error, please submit step-by-step instructions how you get the error with the exact model. Also please do not include multiple things per issue submission.

**Comment by precise-simulation** [comment]
Different grid, different results, especially for such sensitive quantities as discontinuous gradients.
