### ISSUE TITLE
Slice Plot Key/Legend

### ISSUE THREAD

**Issue by rpandress** [precise-simulation/featool-multiphysics#32]
The script below should build and solve a problem and display a the following slice plot:

![sliceplot](https://user-images.githubusercontent.com/89186213/140840235-2613aea2-87ba-4112-a95b-857053455d14.png)

[sliceplot.fes.txt](https://github.com/precise-simulation/featool-multiphysics/files/7500957/sliceplot.fes.txt)

How do I get a better legend? 

Kind regards,
Randal

**Comment by precise-simulation** [comment]
Thank you for the issue report, currently the 3D slice plots produce slight different colorbar ticks per subdomain. This will be corrected in the next update. In the meantime you can reduce the number of ticks with something like the following:

    h_cb = findall(0, 'Tag', 'fea_colorbar');
    h_cb.Ticks = h_cb.Ticks(1:2:length(h_cb.Ticks));

**Comment by rpandress** [comment]
Thanks for the tip!
-Randal
