### ISSUE TITLE
Can Featool include an additional constraint?

### ISSUE THREAD

**Issue by Twinkle2013** [precise-simulation/featool-multiphysics#8]
Can Featool include an additional constraint? For example, there are three variables c, c2 and c3. Would it be possible that an additional constraint can be used so that c=c2+c3 at each grid?

**Comment by precise-simulation** [comment]
Hi, if _c = c2 + c3_ at _every grid point_ then _c_ is not a solution/dependent variable since its completely determined by _c2_ and _c3_, right? Can you clarify how _c_ would be a solution variable, maybe I'm missing something here?
